<?php
/**
 * Copyright © Lyra Network.
 * This file is part of Mi Cuenta Web plugin for Magento 2. See COPYING.md for license details.
 *
 * @author    Lyra Network (https://www.lyra.com/)
 * @copyright Lyra Network
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<ul class="form-list"
    id="payment_form_<?php echo $block->escapeHtml($block->getMethodCode()); ?>"
    style="display: none;">
<?php
if ($block->isLocalCcType()) :
    $cards = $block->getAvailableCcTypes();
    $single = count($cards) === 1;

    // Show card logos as radio buttons.
    $first = true;
    $html = '';
    foreach ($cards as $code => $label) {
        $html .= '<div class="micuentaweb-card">';

        if ($single) {
            $html .= '<input type="hidden" id="micuentaweb_multi_cc_type_' . $block->escapeHtml($code)
                . '" value="' . $block->escapeHtml($code) . '" name="payment[micuentaweb_multi_cc_type]" />' ;
        } else {
            $html .= '<input type="radio" class="radio" id="micuentaweb_multi_cc_type_' . $block->escapeHtml($code)
                . '"' . ($first ? ' checked="checked"' : '') . ' value="'
                . $block->escapeHtml($code) . '" name="payment[micuentaweb_multi_cc_type]" />' ;
        }

        $first = false;
        $ccImageSrc = $block->getCcTypeImageSrc($code);

        $label = $ccImageSrc ? '<img alt="' . $block->escapeHtml($label) . '"
                                     src="' . $block->escapeHtml($ccImageSrc) . '"
                                     title="' . $block->escapeHtml($label) . '" />'
                    : "<span>" . $block->escapeHtml($label) . "</span>";

        $html .= '<label for="micuentaweb_multi_cc_type_' . $block->escapeHtml($code) . '">'
                    . $label .
                  '</label>';
        $html .= '</div>';
    }

    echo '<li>' . $html . '</li>';
endif;
?>

    <li>
        <?php
        $options = $block->getAvailableOptions();

        $oneOption = count($options) === 1;
        $first = true;

        foreach ($options as $key => $option) {
            if ($oneOption) { ?>
                <input type="hidden"
                       id="option_<?php echo $block->escapeHtml($key); ?>"
                       value="<?php echo $block->escapeHtml($key); ?>"
                       name="payment[micuentaweb_multi_option]" />
            <?php } else { ?>
                <input class="radio"
                       type="radio"
                       <?php if ($first) { ?> checked="checked"<?php } ?>
                       id="option_<?php echo $block->escapeHtml($key); ?>"
                       value="<?php echo $block->escapeHtml($key); ?>"
                       name="payment[micuentaweb_multi_option]" />
            <?php
                $first = false;
            }
            ?>

            <label style="float: none;"><?php echo $block->escapeHtml($option['label']); ?></label>
            <br style="margin-bottom: 5px;" />
        <?php } ?>
    </li>
</ul>