<?php
/**
 * Copyright © Lyra Network.
 * This file is part of Mi Cuenta Web plugin for Magento 2. See COPYING.md for license details.
 *
 * @author    Lyra Network (https://www.lyra.com/)
 * @copyright Lyra Network
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<html>
<head></head>

<body>
<?php echo $block->getLoaderHtml(); ?>

<script>
    if (window.top) {
        window.top.location = "<?php echo $block->getForwardUrl(); ?>";
    } else {
        window.location = "<?php echo $block->getForwardUrl(); ?>";
    }
</script>

</body>
</html>