<?php
/**
 * Copyright © Lyra Network.
 * This file is part of Mi Cuenta Web plugin for Magento 2. See COPYING.md for license details.
 *
 * @author    Lyra Network (https://www.lyra.com/)
 * @copyright Lyra Network
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<p><b>
    <?php echo $block->escapeHtml($block->getMethod()->getTitle()); ?>

    <?php
    $payment = $block->getInfo();

    if (stripos($payment->getMethod(), 'micuentaweb_multi') === 0) {
        // Payment in installments, show selected option.
        $option = $payment->getAdditionalInformation(\Lyranetwork\Micuentaweb\Helper\Payment::MULTI_OPTION);
        if (is_string($option)) {
            $option = @unserialize($option);
        }

        if (isset($option) && is_array($option)) {
            echo '<br />';
            echo $block->escapeHtml($option['label'] . ' (' . $option['count'] . 'X)');
        }
    } elseif ($payment->getMethod() === 'micuentaweb_oney') {
        // Oney payment, show selected Oney option.
        $option = $payment->getAdditionalInformation(\Lyranetwork\Micuentaweb\Helper\Payment::ONEY_OPTION);
        if (is_string($option)) {
            $option = @unserialize($option);
        }

        if (isset($option) && is_array($option)) {
            echo '<br />';
            echo $block->escapeHtml($option['label']);
        }
    } elseif (stripos($payment->getMethod(), 'micuentaweb_other') === 0) {
        // Other payment means, show selected option.
        $option = $payment->getAdditionalInformation(\Lyranetwork\Micuentaweb\Helper\Payment::OTHER_OPTION);
        if (is_string($option)) {
            $option = @unserialize($option);
        }

        if (isset($option) && is_array($option)) {
            echo '<br />';
            echo $block->escapeHtml($option['label'] . ' (' . $option['means'] . ')');
        }
    }
    ?>
</b></p>

<?php
if ($payment->getCcTransId()) {
    echo '<br />';

    echo '<b>' . __('Transaction ID') . ': </b>' . $block->escapeHtml($payment->getCcTransId());
    echo '<br />';

    if ((stripos($payment->getMethod(), 'micuentaweb_multi') === false) && ($payment->getCcType() !== 'MULTI')) {
        echo '<b>' . __('Transaction UUID') . ': </b>' .
            $block->escapeHtml($payment->getAdditionalInformation(\Lyranetwork\Micuentaweb\Helper\Payment::TRANS_UUID));
        echo '<br />';
    }

    if ($payment->getCcType() === 'MULTI') { // Multi brand.
        echo $block->getMultiPaymentDetailsHtml(false);
    } else {
        echo $block->getPaymentDetailsHtml(false);
    }
}